### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by VladSmorodsky** [VladSmorodsky/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by VSmorodskiy** [comment]
Programming langueges: PHP, JS
CMS: Magento2, Wordpress (WooCommerce)
Technologies: jQuery, Bootstrap
OS: Linux
Other: HTML, CSS, GIT, OOP, SOLID, Apache2
