### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by VladSmorodsky** [VladSmorodsky/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by VSmorodskiy** [comment]
t: 099-45-67-890
email: binary_student+test@example.com
facebook: test_binary_acad_user
