### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by VladSmorodsky** [VladSmorodsky/homepage#8]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by VladSmorodsky** [comment]
I'm a positive, self-organized person. My hobby is programming, reading books, table tennis, quizzes and quests. I like to do and learn something new and it's connected with all aspects of my life.

**Comment by VSmorodskiy** [comment]
Changed: 
I'm a positive, responsible and self-organized person. My hobby is programming, reading books, table tennis, quizzes and quests. I like to do and learn something new and it's connected with all aspects of my life.
